[rusk_main]
processor_queue_length = 1000

[content_repository]
base_path = "/tmp/rusk/content_repository"
file_name_prefix = "wal"
server_port = 5056
queue_size = 1000

[web_server]
server_port = 5057
