apiVersion: apps/v1
kind: Deployment
metadata:
  name: rusk-main
  namespace: rusk
  labels:
    app: rusk-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rusk-main
  template:
    metadata:
      labels:
        app: rusk-main
    spec:
      containers:
      - name: rusk-main
        image: localhost:5000/rusk_main:latest
        ports:
        - containerPort: 5057
          name: rusk-main-svc
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: rusk-main-service
  namespace: rusk
spec:
  ports:
  - protocol: TCP
    port: 5057
    targetPort: rusk-main-svc
  selector:
    app: ruks-main
  type: ClusterIP
