apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-repository
  namespace: rusk
  labels:
    app: content-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-repository
  template:
    metadata:
      labels:
        app: content-repository
    spec:
      containers:
      - name: content-repository
        image: localhost:5000/rusk_content_repo:latest
        ports:
        - containerPort: 5056
          name: content-repository-svc
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: content-repository-service
  namespace: rusk
spec:
  ports:
  - protocol: TCP
    port: 5056
    targetPort: content-repository-svc
  selector:
    app: content-repository
  type: ClusterIP
