apiVersion: apps/v1
kind: Deployment
metadata:
  name: rusk-client
  namespace: rusk
  labels:
    app: rusk-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rusk-client
  template:
    metadata:
      labels:
        app: rusk-client
    spec:
      containers:
      - name: rusk-client
        image: localhost:5000/rusk_client:latest
        env:
        - name: CONTENT_REPOSITORY_SERVICE
          value: content-repository-service
        ports:
        - containerPort: 80
          name: rusk-client-svc
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: rusk-client-service
  namespace: rusk
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: rusk-client-svc
    nodePort: 30002
  selector:
    app: rusk-client
