apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-repository
  labels:
    app: content-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-repository
  template:
    metadata:
      labels:
        app: content-repository
    spec:
      containers:
      - name: content-repository
        image: content-repository:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
